import {sqliteAdapter} from '../src/sqlite-adapter.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {newRoom,addPlayer,apply,advance,view} from '../src/engine.mjs';import {api} from '../src/api.mjs';
function fixture(n=4){let now=1000;const r=newRoom('ABC234',now);const players=Array.from({length:n},(_,i)=>addPlayer(r,'Player '+i,now));const doAction=(i,type,extra={},time=now)=>{now=time;apply(r,players[i],{type,seq:players[i].seq+1,...extra},now,()=>0)};return {r,players,doAction}}
test('host, minimum players, full room, roles and secret redaction',()=>{const {r,players:p,doAction:a}=fixture(2);assert.throws(()=>a(1,'start'),/host/);assert.throws(()=>a(0,'start'),/3 players/);for(let i=2;i<6;i++)addPlayer(r,'P'+i,1000);assert.throws(()=>addPlayer(r,'Extra',1000),/full/);a(0,'start');assert.equal(r.players.filter(p=>p.role==='impostor').length,1);const v=view(r,p[1],1000);assert.equal(v.role,'crew');assert.ok(v.players.every(q=>!('role'in q)&&!('token'in q)));assert.throws(()=>addPlayer(r,'Late',1000),/started/)});
test('movement respects walls, speed and server role checks',()=>{const {r,players:p,doAction:a}=fixture();a(0,'start');p[1].x=180;p[1].y=275;apply(r,p[1],{type:'input',dx:1,dy:0},1200);assert.ok(p[1].x<=213.001);assert.throws(()=>apply(r,p[1],{type:'input',dx:Infinity,dy:0},1300),/movement/);assert.throws(()=>a(1,'kill',{target:p[2].id},22000),/impostor/);assert.throws(()=>a(0,'repair',{station:0}),/cannot repair/);assert.throws(()=>a(1,'complete'),/Start a repair/)});
test('shared tasks and task win',()=>{const {r,players:p,doAction:a}=fixture();a(0,'start');const pts=[[120,125],[775,125],[120,465],[775,465]];pts.forEach(([x,y],station)=>{Object.assign(p[1],{x,y});a(1,'repair',{station},2000+station*2000);assert.throws(()=>a(1,'complete',{},2100+station*2000),/switches/);a(1,'complete',{},3000+station*2000)});assert.equal(r.phase,'ended');assert.equal(r.winner,'crew')});
test('kill cooldown, reporting, discussion, voting and rematch',()=>{const {r,players:p,doAction:a}=fixture();a(0,'start');assert.throws(()=>a(0,'kill',{target:p[1].id}),/cooling/);a(0,'kill',{target:p[1].id},22000);assert.equal(p[1].alive,false);assert.equal(r.bodies.length,1);assert.equal(r.phase,'playing');assert.throws(()=>a(1,'meeting'),/spectating/);a(2,'report',{},23000);assert.equal(r.phase,'meeting');assert.throws(()=>a(2,'vote',{target:p[0].id},23500),/Discuss/);a(2,'chat',{text:'I saw Player 0.'},24000);a(0,'vote',{target:'skip'},36000);a(2,'vote',{target:p[0].id},36000);a(3,'vote',{target:p[0].id},36000);assert.equal(r.winner,'crew');a(0,'rematch',{},37000);assert.equal(r.phase,'lobby');assert.ok(r.players.every(p=>p.alive))});
test('tie skips; timeout and disconnect produce shared outcomes',()=>{let {r,players:p,doAction:a}=fixture();a(0,'start');p[2].x=450;p[2].y=270;a(2,'meeting',{},5000);a(0,'vote',{target:p[1].id},18000);a(1,'vote',{target:p[0].id},18000);a(2,'vote',{target:'skip'},18000);a(3,'vote',{target:'skip'},18000);assert.equal(r.phase,'playing');assert.ok(p.every(q=>q.alive));p.forEach(q=>q.seen=300000);advance(r,300000);assert.equal(r.winner,'impostor');({r,players:p,doAction:a}=fixture());a(0,'start');p.slice(1).forEach(q=>q.seen=32000);advance(r,32000);assert.equal(r.winner,'crew');assert.equal(r.host,p[1].id)});
test('API independent clients, concurrent joins, authentication and idempotency',async()=>{const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_cool_shard.sql',import.meta.url),'utf8'));const db=sqliteAdapter(sql);const call=async(path,body)=>{const res=await api(new Request('https://game.test/api/'+path,{method:'POST',body:JSON.stringify(body)}),db);return {status:res.status,...await res.json()}};const host=await call('create',{name:'Host'});assert.equal(host.status,200);const code=host.state.code;const joins=await Promise.all(['A','B','C','D','E'].map(name=>call('join',{code,name})));assert.ok(joins.every(j=>j.status===200));assert.equal((await call('join',{code,name:'Full'})).status,400);assert.equal((await call('sync',{code,token:'wrong',action:{type:'input',dx:0,dy:0}})).status,401);const start={code,token:host.token,action:{type:'start',seq:1}};const started=await call('sync',start);assert.equal(started.state.players.length,6);assert.equal(started.state.phase,'playing');const duplicate=await call('sync',start);assert.equal(duplicate.status,200);const states=await Promise.all(joins.map(j=>call('sync',{code,token:j.token,action:{type:'input',dx:0,dy:0}})));assert.ok(states.every(s=>s.state.phase==='playing'));assert.equal([started,...states].filter(s=>s.state.role==='impostor').length,1);assert.ok(states.every(s=>s.state.players.every(p=>!p.token&&!p.role)));sql.close()});
